### PR TITLE
feat: add a new UI SIG

### PR DESCRIPTION
**Pull request by ankitm123**
Signed-off-by: ankitm123 <ankitmohapatra123@gmail.com>

### CODE REVIEW

**Comment by ankitm123** [comment]
Suggestions welcome for
- Sig chair
- meeting cadence (which weekday we want to meet and frequency - bi weekly may be ok)

**Review by tomhobson — APPROVED** [review]
LGTM!

**Comment by babadofar** [comment]
👍

**Comment by aabhas-sao** [comment]
👍

**Pull request merged**
